worker_processes auto;

events {
    worker_connections 1024;
}

http {

    server {
        listen 20000;


        location = /api/Save-JSON {
            proxy_pass http://127.0.0.1:40000/NGINX-test;
        }

        location / {
            root "C:\Users\litvi\Documents\BSTU\3\2\Технологии разработки веб-приложений\2";
            index TDWA02-01.html index.html;
        }

        location /TDWA02-02/ {
            alias "C:/Users/litvi/Documents/BSTU/3/2/Технологии разработки веб-приложений/2/tdwa02-02/build/";
            index index.html;
            try_files $uri $uri/ /index.html;

        }
    }
}